# Generated by Django 4.2 on 2024-12-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Введите фамилию рабочего",
                        max_length=150,
                        verbose_name="Фамилия рабочего",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя рабочего",
                        max_length=150,
                        verbose_name="Имя рабочего",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество рабочего",
                        max_length=150,
                        null=True,
                        verbose_name="Отчество рабочего",
                    ),
                ),
                (
                    "brigade_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Введите номер бригады",
                        null=True,
                        verbose_name="Номер бригады",
                    ),
                ),
                (
                    "wages",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Введите заработную плату рабочего",
                        null=True,
                        verbose_name="Зарплата рабочего",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Введите специализацию рабочего",
                        max_length=100,
                        null=True,
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочий",
                "verbose_name_plural": "Рабочие",
            },
        ),
    ]
