# Generated by Django 4.2 on 2024-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brigade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Введите номер бригады",
                        unique=True,
                        verbose_name="Номер бригады",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания записи заполняется автоматически",
                        verbose_name="Дата создания записи",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIN", "Чистовая отделка"),
                            ("RF", "Черновая отделка"),
                        ],
                        help_text="Введите специализацию бригады",
                        max_length=100,
                        null=True,
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бригада",
                "verbose_name_plural": "Бригады",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Введите фамилию рабочего",
                        max_length=150,
                        verbose_name="Фамилия рабочего",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя рабочего",
                        max_length=150,
                        verbose_name="Имя рабочего",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество рабочего",
                        max_length=150,
                        null=True,
                        verbose_name="Отчество рабочего",
                    ),
                ),
                (
                    "wages",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Введите заработную плату рабочего",
                        null=True,
                        verbose_name="Зарплата рабочего",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата создания записи заполняется автоматически",
                        verbose_name="Дата создания записи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WR", "Рабочий"),
                            ("FR", "Бригадир"),
                            ("SCH", "Прораб"),
                        ],
                        help_text="Выберите статус рабочего",
                        max_length=50,
                        verbose_name="Статус рабочего",
                    ),
                ),
                (
                    "brigade",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите бригаду",
                        null=True,
                        to="workers.brigade",
                        verbose_name="Бригада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочий",
                "verbose_name_plural": "Рабочие",
            },
        ),
        migrations.DeleteModel(
            name="Vorker",
        ),
    ]
